### ISSUE TITLE
Coding profiles and link to the mobile number

### ISSUE THREAD

**Issue by safinghoghabori** [kevalmorabia97/Latex-Resume-Keval-Morabia#2]
Can you please tell me how can I add coding profiles into the header section or create a new section? Also, how can I make a mobile number as a link?

**Comment by kevalmorabia97** [comment]
You can make phone number a link by changing `xxx-xxx-xxxx` to `\href{tel:xxx-xxx-xxxx}{xxx-xxx-xxxx}`

**Comment by kevalmorabia97** [comment]
You can make a new section as follows:

```
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%     CODING PROFILES
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section{Coding Profiles} 
\hrulefill 

\pt Profile 1
\pt Profile 2
\sectionsep
```

**Comment by safinghoghabori** [comment]
First of all, thank you. Also, i have more two questions, 

1. can i add coding profiles in the header section itself? Will it be bad? 
2. There are links in the resume, but it does not have an underline or anything. So the recruiter will be able to identify that there is a link? or i should add an underline too?

**Comment by kevalmorabia97** [comment]
You can add underline as well if you like it. No harm in that.

To add coding profile on the header, you would have to remove something else to make space. You can check for available fonts at http://mirrors.ibiblio.org/CTAN/fonts/fontawesome5/doc/fontawesome5.pdf and see if any is relevant for it and update https://github.com/kevalmorabia97/Latex-Resume-Keval-Morabia/blob/master/Resume.tex#L22 line with it

**Comment by safinghoghabori** [comment]
Ok, I'll try it out. 

Unfortunately, i have to use some other template:( because I'm a 2023 pass out and i don't have many details to show. I added my all details even my 10th, and 12th-grade details but still resume has almost 2 section space left at the bottom, which is bad I guess. 

Let me know if you have any idea that I can use the same template though. I really really loved this template. 

Here I'm attaching an image of how much space is still i need to fill, which i don't know what should i add to fill...

![image](https://user-images.githubusercontent.com/51900017/186871413-25129942-9d95-45c9-b74d-207aa50c2ca1.png)

**Comment by kevalmorabia97** [comment]
A very easy thing to do would be to increase heading font size and space between lines in `Resume.cls`. That can very easily fill most of the page and still make it look good

**Comment by safinghoghabori** [comment]
Still remains spaces. 

One more doubt, if we make changes to the resume template or if there are any unsolved errors while using LaTeX on overleaf, does it make the resume unstructured and hence won't get shortlisted?

**Comment by kevalmorabia97** [comment]
As long as it looks good and there aren't any big errors, you should be fine

**Comment by safinghoghabori** [comment]
Okay. Thank you.
